 platform :ios, '9.0'

target 'SwiftUIAgora' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SwiftUIAgora

  target 'SwiftUIAgoraUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
